version: "3.8"

services:
  sticky-notes-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sticky-notes-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - STORAGE_TYPE=${STORAGE_TYPE:-file}
      - DATA_BASE_PATH=/app/data
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - AUTH_ENABLED=${AUTH_ENABLED:-false}
      - AUTH_TOKEN=${AUTH_TOKEN:-}
    volumes:
      # Persist data directory
      - ./data:/app/data
      # Optional: mount custom config
      # - ./config.js:/app/config.js:ro
    networks:
      - sticky-notes-network
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/api/health', (r) => { process.exit(r.statusCode === 200 ? 0 : 1); })",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  sticky-notes-network:
    driver: bridge

volumes:
  sticky-notes-data:
    driver: local
